// Generated by CoffeeScript 1.3.3
(function() {
  var colors, columns, height, i, left, margin, tile, tileCount, tileHeight, tileViews, tileWidth, top, width;

  margin = 15;

  columns = 3;

  tileCount = 100;

  width = window.innerWidth;

  tileWidth = (width - (columns + 1) * margin) / columns;

  tileHeight = tileWidth * 1.5;

  height = (tileHeight + margin) * Math.ceil(1.0 * tileCount / columns) + margin;

  colors = ['#ff695a', '#f9a77c', '#579092', '#3695d8', '#d998a6', '#dc4537', '#fff280', '#94c59c', '#3b5065', '#b75468'];

  document.body.style.height = height + 'px';

  tileViews = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; 0 <= tileCount ? _i < tileCount : _i > tileCount; i = 0 <= tileCount ? ++_i : --_i) {
      left = margin + (i % columns) * (tileWidth + margin);
      top = margin + Math.floor(i / columns) * (tileHeight + margin);
      tile = document.createElement('div');
      tile.className = 'tile';
      tile.style.left = left + 'px';
      tile.style.top = top + 'px';
      tile.style.width = tileWidth + 'px';
      tile.style.height = tileHeight + 'px';
      tile.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
      _results.push(document.body.appendChild(tile));
    }
    return _results;
  })();

}).call(this);
